PROJECT         := PdbTest
DEVICES         := LPC1768
GCC4MBED_DIR    := ../../gcc4mbed
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 0
GCC4MBED_TYPE   := Develop

MBED_OS_ENABLE  := 0
#MRI_ENABLE      := 1
#MRI_UART        := MRI_UART_MBED_USB MRI_UART_BAUD=230400

include $(GCC4MBED_DIR)/build/gcc4mbed.mk

