[package]
name = "cv_test"
version = "0.1.0"
authors = ["Adam Green <adamgreen@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.48"
